### ISSUE TITLE
Angular 13: Uncaught TypeError: Cannot set property accessToken of [object Module] which has only a getter

### ISSUE THREAD

**Issue by Merk42** [Wykks/ngx-mapbox-gl#373]
I upgraded to version 8.0.0 to get it working for Angular 13, but it still doesn't work. I get the following error:
`Uncaught TypeError: Cannot set property accessToken of [object Module] which has only a getter`

I've tried the solutions here: https://stackoverflow.com/questions/44332290/mapbox-gl-typing-wont-allow-accesstoken-assignment

I've tried moving the token from `NgxMapboxGLModule.withConfig({accessToken: 'myaccesstoken'})` to `<mgl-map accessToken="myaccesstoken">`

I've even tried removing any reference to an accesstoken at all.

Nothing works, all the same error.

**Comment by johanur-rahman** [comment]
Facing the same issue

**Comment by Gobbenobber** [comment]
Same issue here. Not even sure how to circumvent  :/

**Comment by mokeddes** [comment]
Facing the same issue

**Comment by Thanhwebdev** [comment]
I too am facing the same issue.

**Comment by bdirito** [comment]
Also an issue in angular 14 (though it doesn't appear to have anything to do with angular).

**Comment by mokeddes** [comment]
I found some workaround and i have submit a [PR](https://github.com/Wykks/ngx-mapbox-gl/pull/374)

**Comment by johanur-rahman** [comment]
> 

Its great that you have updated the 'rxjs' version as well. 

Waiting for it to be approved

**Comment by ciukstar** [comment]
Same issue I see in my console:
```
Uncaught TypeError: Cannot set property accessToken of [object Module] which has only a getter
    at MapService.assign (ngx-mapbox-gl.mjs:772:13)
    at Object.next (ngx-mapbox-gl.mjs:28:18)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at throwIfEmpty.js:9:24
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at take.js:12:32
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
```
Env:
```
$ npm list ngx-mapbox-gl
...
└── ngx-mapbox-gl@8.0.0
```
```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.2
Node: 14.17.0
Package Manager: npm 8.12.1 
OS: linux x64

Angular: 14.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.4
```

**Comment by mokeddes** [comment]
> Same issue I see in my console:
> ```
> Uncaught TypeError: Cannot set property accessToken of [object Module] which has only a getter
>     at MapService.assign (ngx-mapbox-gl.mjs:772:13)
>     at Object.next (ngx-mapbox-gl.mjs:28:18)
>     at ConsumerObserver.next (Subscriber.js:91:33)
>     at SafeSubscriber._next (Subscriber.js:60:26)
>     at SafeSubscriber.next (Subscriber.js:31:18)
>     at throwIfEmpty.js:9:24
>     at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
>     at OperatorSubscriber.next (Subscriber.js:31:18)
>     at take.js:12:32
>     at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
> ```
> Env:
> ```
> $ npm list ngx-mapbox-gl
> ...
> └── ngx-mapbox-gl@8.0.0
> ```
> ```
> $ npm list mapbox-gl
> ...
> ├─┬ @mapbox/mapbox-gl-geocoder@5.0.1
> │ └── mapbox-gl@2.9.0 deduped
> ├─┬ @mapbox/mapbox-gl-language@1.0.0
> │ └── mapbox-gl@2.9.0 deduped
> ├── mapbox-gl@2.9.0
> └─┬ ngx-mapbox-gl@8.0.0
>   └── mapbox-gl@2.9.0 deduped
> ```
> ```
> $ ng version
> 
>      _                      _                 ____ _     ___
>     / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
>    / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
>   / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
>  /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
>                 |___/
>     
> 
> Angular CLI: 14.0.2
> Node: 14.17.0
> Package Manager: npm 8.12.1 
> OS: linux x64
> 
> Angular: 14.0.2
> ... animations, cdk, cli, common, compiler, compiler-cli, core
> ... forms, language-service, material, platform-browser
> ... platform-browser-dynamic, router
> 
> Package                         Version
> ---------------------------------------------------------
> @angular-devkit/architect       0.1400.2
> @angular-devkit/build-angular   14.0.2
> @angular-devkit/core            14.0.2
> @angular-devkit/schematics      14.0.2
> @angular/flex-layout            13.0.0-beta.38
> @schematics/angular             14.0.2
> rxjs                            7.5.5
> typescript                      4.7.4
> ```

I make a PR with fix ( workround)

**Comment by Wykks** [comment]
Fix released under v8.0.1, thanks @mokeddes

**Comment by vladkasianenko** [comment]
According to [this Changelog](https://github.com/Wykks/ngx-mapbox-gl/blob/dfb9244af28f81806f69573f68ef867cab1e3be4/CHANGELOG.md), there's no version 8.0.1.

Now I have 9.1.0 and still experience this issue.
